---
#- name: Include distribution dependent variables
#  include_vars: "{{ item }}"
#  with_first_found:
#    - "{{ ansible_distribution }}.yml"
#    - "{{ ansible_os_family }}.yml"
#  tags: postgres
- include_tasks: redhat.yml
  when:
    - ansible_os_family == "RedHat"

- include_tasks: ubuntu.yml
  when:
    - ansible_distribution == "Ubuntu"

- include_tasks: config.yml
- include_tasks: databases.yml
- include_tasks: users.yml

- name: Check is replication necessary
  stat:
    path: "{{ postgresql_pgdata }}/standby.signal"
  register: standby_signal

- include_tasks: initreplication.yml
  when:
    - init_replication
    - not standby_signal.stat.exists


