---
- name: Check stanza state
  ansible.builtin.stat:
    path: "{{ postgresql_pgbackrest_repo_path }}/archive/{{ stanza }}/archive.info"
  register: stanza_state

- name: Create stanza
  become_user: "{{ postgresql_user_name }}"
  ansible.builtin.shell:
    cmd: "{{ pgbackrest_path.stdout }} stanza-create --stanza={{ stanza }} --db-port={{ postgresql_port }} --log-level-console=info"
  when:
    - not stanza_state.stat.exists
    - not postgresql_init_replication
