# postgres/handlers/main.yml
---
- name: Reload PostgreSQL
  ansible.builtin.service:
    name: "{{ postgresql_service_name }}"
    state: reloaded

- name: Restart PostgreSQL
  ansible.builtin.service:
    name: "{{ postgresql_service_name }}"
    state: restarted

- name: Dnf_cache
  ansible.builtin.yum:
    update_cache: yes
