# postgres/handlers/main.yml
---
- name: Reload PostgreSQL
  service:
    name: "{{ postgresql_service_name }}"
    state: reloaded
- name: Restart PostgreSQL
  service:
    name: "{{ postgresql_service_name }}"
    state: restarted
- name: dnf_cache
  yum:
    update_cache: yes
