# postgres/molecule/docker/molecule.yml
---
dependency:
  name: galaxy
driver:
  name: docker

lint: |
  yamllint -c molecule/tests/yamllint.yml .
  ansible-lint -v -c molecule/tests/lint.yml .

platforms:
  - name: postgres-centos8
    groups:
      - postgres
    image: "geerlingguy/docker-centos8-ansible"
    image_version: latest
    privileged: true
    tty: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    command: "/lib/systemd/systemd"
    pre_build_image: true
    port_bindings:
      5432: 54322

provisioner:
  name: ansible
  config_options:
    defaults:
      allow_world_readable_tmpfiles: True
      pipelining: True
  lint:
    name: |
      yamllint -c molecule/tests/yamllint.yml .
      ansible-lint -v -c molecule/tests/lint.yml .
  inventory:
    group_vars:
      postgres:
        postgresql_version: 14
        postgresql_use_ssl: true
        postgresql_ssl_DH_size: 2048
        postgresql_install_postgis: true
        postgresql_network_password_mode: 'scram-sha-256'
        postgresql_conf:
          - listen_addresses: "'0.0.0.0'"
          - max_connections: '200'       # decrease connection limit
          - password_encryption: 'scram-sha-256'
          #- max_wal_senders: 5
          #- max_replication_slots: 5
          - ssl: "on"
          - ssl_ca_file: "'{{ postgresql_conf_dir }}/{{ postgresql_ssl_ca }}'"
          - ssl_cert_file: "'{{ postgresql_conf_dir }}/{{ postgresql_ssl_crt }}'"
          - ssl_key_file: "'{{ postgresql_conf_dir }}/{{ postgresql_ssl_key }}'"
          - ssl_ciphers: "'HIGH:MEDIUM:+3DES:!aNULL'"
          # ssl_dh_params_file - not exists in 9.6, 10(Centos)
          - ssl_dh_params_file: "'{{ postgresql_conf_dir }}/{{ postgresql_ssl_dh }}'"
          - ssl_prefer_server_ciphers: "on"
          - ssl_min_protocol_version: 'TLSv1.1'  # not exists in 9.6
          - ssl_max_protocol_version: 'TLSv1.2'  # not exists in 9.6
          - log_destination: "'syslog'"
          - log_filename: "'postgresql-%a.log'"
          - syslog_facility: "'LOCAL0'"
          - syslog_ident: "'postgres'"
          - syslog_sequence_numbers: on
          - syslog_split_messages: on
        postgresql_global_users:
          - user: "replicator"
            # password: "titok123"
            # ssl_mode: require
            role_attr_flags: "NOSUPERUSER,NOCREATEROLE,NOCREATEDB,INHERIT,LOGIN,REPLICATION"

        postgresql_pg_hba_conf:
          #  - "hostssl	replication		replicator		0.0.0.0/0		trust"
          #  - "host	replication		replicator		0.0.0.0/0		trust"
          #  - "host	replication		replicator		0.0.0.0/0		scram-sha-256"
          - "hostssl	demo		bull		0.0.0.0/0		scram-sha-256"
          - "host   	demo		bull		0.0.0.0/0		scram-sha-256"
          #  - "hostssl	demo		bull		0.0.0.0/0		md5"
          #  - "host   	demo		bull		0.0.0.0/0		md5"

        postgresql_dbs:
          - name: "demo"
            password: "secret123"
            user: "bull"
            encoding: UTF-8
            locale: en_US.UTF-8
            lc_collate: en_US.UTF-8

        postgresql_install_pg_audit: true
        postgresql_pgaudit_redhat_package: pgaudit16_14
        postgresql_install_pg_rman: false
        postgresql_extra_packages:
         # - "postgresql-plperl-{{ postgresql_version }}"
          - nfs-utils

verifier:
  #name: ansible
  name: testinfra
  lint:
    name: flake8
  options:
    sudo: true
    v: 1
  directory: ../tests

#additional_files_or_dirs:
  #    - ../path/to/test_1.py
  #    - ../path/to/test_2.py
  #    - ../path/to/directory/*

scenario:
  create_sequence:
    # - dependency # not configured yet.
    - create
    - prepare
  check_sequence:
    - dependency # not configured yet.
    # - cleanup # not configured yet.
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency # not configured yet.
    - lint
    - create
    - prepare
    - converge
  destroy_sequence:
    #- dependency # not configured yet.
    #- cleanup # not configured yet.
    - destroy
  test_sequence:
    - dependency # not configured yet.
    - lint
    # - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    # - side_effect # not configured yet.
    - verify
    # - cleanup # not configured yet.
    - destroy
